### ISSUE TITLE
Wallet extension not opened on browser

### ISSUE THREAD

**Issue by Fiftyw3bs** [geniusyield/atlas-docs#71]
The documentation suggests to run the docs locally in order to try out the contract. But, selecting either Nami or Ethernl, after running it locally, doesn't trigger the wallets to open.

**Comment by sourabhxyz** [comment]
Weird, which version of Atlas are you using? Is it the latest, 0.4.0?

Also, unfortunately, the docs are outdated and need to be updated in sync with recent Atlas changes. This is prioritised on our end.

**Comment by Fiftyw3bs** [comment]
Hi @sourabhxyz, thanks for the response.

Yes, I'm using the release version v0.4.0... Looking forward to a fix.

Thanks, once again.

**Comment by sourabhxyz** [comment]
Thanks for letting me know @Fiftyw3bs, I'll take a look on Monday 👍

**Comment by sourabhxyz** [comment]
@Fiftyw3bs wallet popup is suppose to happen when you initiate an operation. For instance, for operation, "**_Enter the address to put Reference Script at_**", does wallet popup happen when you enter address and click on "Submit"? Note that wallet logic is available [here](https://github.com/geniusyield/atlas-docs/blob/main/src/components/browser-integration.tsx).

**Comment by Fiftyw3bs** [comment]
HI @sourabhxyz, it turns out I was submitting the wrong form.
